databases:
  - name: notes
    databaseName: notes
    user: notes

services:
  - type: web
    name: notes
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn notes.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: notes
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4