# Generated by Django 3.1.7 on 2023-04-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_alter_nota_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
