# Generated by Django 4.2 on 2023-04-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0006_auto_20230417_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
